### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by ghost** [gantrim/node-teradata#11]
If the sql query throws an error, is there any mechanism to handle this?

**Comment by gantrim** [comment]
Since this package uses the bluebird promise library, you should be able to catch any exceptions using the standard [promise].catch(...) convention.  For Example (using bluebird):

```
var Teradata = require("teradata");
var Promise = require("bluebird");

     Teradata.connect('[url]' ,'[user]', '[password]')
         .then(function () {       
             return Teradata.executeQuery("[select query]", [limit]);
         })
         .then(function (update count) {
             console.log("Updated %d records", updateCount);
             return Teradata.disconnect();
        })
         .catch(function (ex) {
             //handle exception
        });
```

Let me know if this resolves your issue.

**Comment by gantrim** [comment]
no response from op. features have been added. closing.
