### ISSUE TITLE
Case error with Teradata.js 

### ISSUE THREAD

**Issue by leogariba** [gantrim/node-teradata#4]
index.js ask for terdata.js but Teradata.js has captal letter T and the module cannot be found.
Just rename Terdata.js to terdata.js

**Comment by gantrim** [comment]
This was fixed and pushed to the release branch [here](https://github.com/gantrim/node-teradata/pull/3/commits/d862890a7da294c56d941741cfb2bdfdb6cf6aa4). I have merged it into master to avoid confusion. Thanks for pointing this out. Let me know if this issue is still a problem for you.

**Comment by leogariba** [comment]
Sorry for reporting an already fixed problem! npm is still installing the previous version.

**Comment by gantrim** [comment]
published fixed version to npm. sorry about that.
