### ISSUE TITLE
Need option to meantion jar filepath

### ISSUE THREAD

**Issue by ghost** [gantrim/node-teradata#8]
Currently, jars folder is required to be present at location from where we are running the script. There should be an option to mention the paths for both the jar files whenever we call Teradata connect. This helps when we schedule the script in some batch or cronjob

**Comment by gantrim** [comment]
I have added this option and updated the readme to reflect this. you should just have to change your connect statement slightly. Please try it out and let me know if your issue has been solved.

**Comment by ghost** [comment]
Thanks for the quick action. Works fine for me. One suggestion, I am using path.resolve to get the full filepath for the jar files which removes the trailing '/' symbol. From the code I see, you append  teradataJarPath variable with *.jar. It would be great if it's handle on the module side. Currently I am appending the '/' symbol once the path is resolved

**Comment by gantrim** [comment]
made the requested change in  #10 . closing issue
